package entity;
// Generated Nov 3, 2019 4:24:27 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category {

    private String categoryId;
    private String categoryName;
    private Set<MovieCategory> movieCategories = new HashSet<MovieCategory>(0);

    public Category() {
    }

    public Category(String categoryId) {
        this.categoryId = categoryId;
    }

    public Category(String categoryId, String categoryName, Set<MovieCategory> movieCategories) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.movieCategories = movieCategories;
    }

    public String getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public Set<MovieCategory> getMovieCategories() {
        return this.movieCategories;
    }

    public void setMovieCategories(Set<MovieCategory> movieCategories) {
        this.movieCategories = movieCategories;
    }

}
