package entity;
// Generated Nov 3, 2019 4:24:27 PM by Hibernate Tools 4.3.1

/**
 * Cinema generated by hbm2java
 */
public class Cinema {

    private String cinemaId;
    private City city;
    private String cinemaName;

    public Cinema() {
    }

    public Cinema(String cinemaId) {
        this.cinemaId = cinemaId;
    }

    public Cinema(String cinemaId, City city, String cinemaName) {
        this.cinemaId = cinemaId;
        this.city = city;
        this.cinemaName = cinemaName;
    }

    public String getCinemaId() {
        return this.cinemaId;
    }

    public void setCinemaId(String cinemaId) {
        this.cinemaId = cinemaId;
    }

    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public String getCinemaName() {
        return this.cinemaName;
    }

    public void setCinemaName(String cinemaName) {
        this.cinemaName = cinemaName;
    }

}
