package entity;
// Generated Nov 3, 2019 4:24:27 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City {

    private String cityId;
    private String cityName;
    private Set<Cinema> cinemas = new HashSet<Cinema>(0);

    public City() {
    }

    public City(String cityId) {
        this.cityId = cityId;
    }

    public City(String cityId, String cityName, Set<Cinema> cinemas) {
        this.cityId = cityId;
        this.cityName = cityName;
        this.cinemas = cinemas;
    }

    public String getCityId() {
        return this.cityId;
    }

    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Set<Cinema> getCinemas() {
        return this.cinemas;
    }

    public void setCinemas(Set<Cinema> cinemas) {
        this.cinemas = cinemas;
    }

}
