package entity;
// Generated Nov 3, 2019 4:24:27 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Graphic generated by hbm2java
 */
public class Graphic {

    private String graphicId;
    private String graphicType;
    private Set<MovieGraphic> movieGraphics = new HashSet<MovieGraphic>(0);

    public Graphic() {
    }

    public Graphic(String graphicId) {
        this.graphicId = graphicId;
    }

    public Graphic(String graphicId, String graphicType, Set<MovieGraphic> movieGraphics) {
        this.graphicId = graphicId;
        this.graphicType = graphicType;
        this.movieGraphics = movieGraphics;
    }

    public String getGraphicId() {
        return this.graphicId;
    }

    public void setGraphicId(String graphicId) {
        this.graphicId = graphicId;
    }

    public String getGraphicType() {
        return this.graphicType;
    }

    public void setGraphicType(String graphicType) {
        this.graphicType = graphicType;
    }

    public Set<MovieGraphic> getMovieGraphics() {
        return this.movieGraphics;
    }

    public void setMovieGraphics(Set<MovieGraphic> movieGraphics) {
        this.movieGraphics = movieGraphics;
    }

}
