package entity;
// Generated Nov 3, 2019 4:24:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hourss generated by hbm2java
 */
public class Hourss  implements java.io.Serializable {


     private String hoursId;
     private String hourss;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);

    public Hourss() {
    }

	
    public Hourss(String hoursId) {
        this.hoursId = hoursId;
    }
    public Hourss(String hoursId, String hourss, Set<Ticket> tickets) {
       this.hoursId = hoursId;
       this.hourss = hourss;
       this.tickets = tickets;
    }
   
    public String getHoursId() {
        return this.hoursId;
    }
    
    public void setHoursId(String hoursId) {
        this.hoursId = hoursId;
    }
    public String getHourss() {
        return this.hourss;
    }
    
    public void setHourss(String hourss) {
        this.hourss = hourss;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }




}


