package entity;
// Generated Nov 3, 2019 4:24:27 PM by Hibernate Tools 4.3.1

/**
 * MovieCategory generated by hbm2java
 */
public class MovieCategory {

    private MovieCategoryId id;
    private Category category;
    private Movie movie;

    public MovieCategory() {
    }

    public MovieCategory(MovieCategoryId id) {
        this.id = id;
    }

    public MovieCategory(MovieCategoryId id, Category category, Movie movie) {
        this.id = id;
        this.category = category;
        this.movie = movie;
    }

    public MovieCategoryId getId() {
        return this.id;
    }

    public void setId(MovieCategoryId id) {
        this.id = id;
    }

    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Movie getMovie() {
        return this.movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

}
