package entity;
// Generated Nov 3, 2019 4:24:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie {

    private String movieId;
    private String movieName;
    private String scenario;
    private String directors;
    private Integer duration;
    private Date release;
    private int moviePrice;
    private String language;
    private String overView;
    private String origin;
    private String videoTrailer;
    private Boolean status;
    private String imageMovie;
    private String categoryName;
    private Set<MovieCategory> movieCategories = new HashSet<>(0);
    private Set<TicketBook> ticketBooks = new HashSet<TicketBook>(0);
    private Set<MovieGraphic> movieGraphics = new HashSet<MovieGraphic>(0);

    public Movie() {
    }

    public Movie(String movieId) {
        this.movieId = movieId;
    }

    public Movie(String movieId, String movieName, String scenario, String directors, Integer duration, Date release,int moviePrice, String language, String overView, String origin, String videoTrailer, Boolean status, String imageMovie,String categoryName, Set<MovieCategory> movieCategories, Set<TicketBook> ticketBooks, Set<MovieGraphic> movieGraphics) {
        this.movieId = movieId;
        this.movieName = movieName;
        this.scenario = scenario;
        this.directors = directors;
        this.duration = duration;
        this.release = release;
        this.moviePrice = moviePrice;
        this.language = language;
        this.overView = overView;
        this.origin = origin;
        this.videoTrailer = videoTrailer;
        this.status = status;
        this.imageMovie = imageMovie;
        this.categoryName = categoryName;
        this.movieCategories = movieCategories;
        this.ticketBooks = ticketBooks;
        this.movieGraphics = movieGraphics;
    }

    public String getMovieId() {
        return this.movieId;
    }

    public void setMovieId(String movieId) {
        this.movieId = movieId;
    }

    public String getMovieName() {
        return this.movieName;
    }

    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }

    public String getScenario() {
        return this.scenario;
    }

    public void setScenario(String scenario) {
        this.scenario = scenario;
    }

    public String getDirectors() {
        return this.directors;
    }

    public void setDirectors(String directors) {
        this.directors = directors;
    }

    public Integer getDuration() {
        return this.duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Date getRelease() {
        return this.release;
    }

    public void setRelease(Date release) {
        this.release = release;
    }

    public int getMoviePrice() {
        return moviePrice;
    }

    public void setMoviePrice(int moviePrice) {
        this.moviePrice = moviePrice;
    }
    
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getOverView() {
        return this.overView;
    }

    public void setOverView(String overView) {
        this.overView = overView;
    }

    public String getOrigin() {
        return this.origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    public String getVideoTrailer() {
        return this.videoTrailer;
    }

    public void setVideoTrailer(String videoTrailer) {
        this.videoTrailer = videoTrailer;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getImageMovie() {
        return this.imageMovie;
    }

    public void setImageMovie(String imageMovie) {
        this.imageMovie = imageMovie;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    public Set<TicketBook> getTicketBooks() {
        return this.ticketBooks;
    }

    public void setTicketBooks(Set<TicketBook> ticketBooks) {
        this.ticketBooks = ticketBooks;
    }

    public Set<MovieCategory> getMovieCategories() {
        return this.movieCategories;
    }

    public void setMovieCategories(Set<MovieCategory> movieCategories) {
        this.movieCategories = movieCategories;
    }

    public Set<MovieGraphic> getMovieGraphics() {
        return this.movieGraphics;
    }

    public void setMovieGraphics(Set<MovieGraphic> movieGraphics) {
        this.movieGraphics = movieGraphics;
    }

}
